### ISSUE TITLE
[Question] Adding `actions-distributed-press` to Quartz Github Action

### ISSUE THREAD

**Issue by errbufferoverfl** [hyphacoop/actions-distributed-press#2]
Hey Jacky,

I recently deployed Quartz via Github Pages and started setting up my own Distributed Press instances so I can play with distributing the content of my mind garden via Hyper and IPFS as well.

I've added this deploy action to my [Quartz Deploy file](https://github.com/errbufferoverfl/garden.errbufferoverfl.me/blob/1d5c3586bc7fd1f9e87a983f859e31735f66cb6b/.github/workflows/deploy.yml).

However, I'm running into a vague error when trying to deploy to my DP instance:

```
Getting ready to deploy distributed.errbufferoverfl.me to https://distributed.errbufferoverfl.me/
Creating tarball...
Uploading new site content...
/home/runner/work/_actions/hyphacoop/actions-distributed-press/v1.1/dist/index.js:14103
    throw new Error(`Failed to upload the contents of the site: ${json}`);
          ^

Error: Failed to upload the contents of the site: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.fetch (/home/press/api.distributed.press/node_modules/ipfs-utils/src/http.js:140:22)
    at async Object.addAll (file:///home/press/api.distributed.press/node_modules/ipfs-http-client/src/add-all.js:36:17)
    at async IPFSProtocol.sync (file:///home/press/api.distributed.press/protocols/ipfs.ts:163:22)
    at async Promise.all (index 1)
    at async SiteConfigStore.sync (file:///home/press/api.distributed.press/config/sites.ts:65:5)
    at async file:///home/press/api.distributed.press/api/sites.ts:178:7
    at async processRequestFiles (file:///home/press/api.distributed.press/api/sites.ts:20:7)
    at async Object.<anonymous> (file:///home/press/api.distributed.press/api/sites.ts:169:12)
    at run (/home/runner/work/_actions/hyphacoop/actions-distributed-press/v1.1/dist/index.js:14103:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I thought that perhaps the problem was with my mind garden having multiple directories or the size of the content so I changed the `publish_dir` to only publish `./public/notes` however I'm experiencing the same problems. (See the current [deploy.yml file](https://github.com/errbufferoverfl/garden.errbufferoverfl.me/blob/1d5c3586bc7fd1f9e87a983f859e31735f66cb6b/.github/workflows/deploy.yml)).

I'm fairly new to distributed publishing and Distributed Press so any insights you might have about what I'm doing wrong would be amazing.

Thanks so much.

**Comment by errbufferoverfl** [comment]
Quick update, I took a look at how `compost.digital` does this and subsequently made some changes to follow a similar pattern. [New deploy action is here for reference](https://github.com/errbufferoverfl/garden.errbufferoverfl.me/blob/ef697ecd79e24f9aebda5c14b0848cbc633d80d7/.github/workflows/distributed-press-publish.yml).

**Comment by jackyzha0** [comment]
Might be a bug with configuring open ports in the Ansible for the self-hosted DP instance. cc @RangerMauve do you know if we did any other port fiddling with our DP instance?

**Comment by errbufferoverfl** [comment]
If it's of any help when here are the nmap results for my DP instance:

```
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https
```

It's a vanilla deployment with no custom firewall etc.

**Comment by jackyzha0** [comment]
> If it's of any help when here are the nmap results for my DP instance:
> 
> ```
> PORT    STATE SERVICE
> 22/tcp  open  ssh
> 80/tcp  open  http
> 443/tcp open  https
> ```
> 
> It's a vanilla deployment with no custom firewall etc.

That's really weird, what does `ufw status` output? 

Here's the relevant part of the Ansible that should have setup the ports: https://github.com/hyphacoop/api.distributed.press/blob/main/ansible/roles/distributed_press/tasks/main.yml#L59-L69

**Comment by errbufferoverfl** [comment]
Yesterday I went through and double checked all of the firewall rules were correctly initiated which they were but I never checked that status of `ufw` only of the nginx and distributed.press services. Checking now, and `ufw` returned `inactive` 😭. 

I've run `ufw enable` and now I'm getting:

```
ufw status
Status: active

To                         Action      From
--                         ------      ----
53/udp                     ALLOW       Anywhere
7976/udp                   ALLOW       Anywhere
7976/tcp                   ALLOW       Anywhere
Nginx Full                 ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
53/udp (v6)                ALLOW       Anywhere (v6)
7976/udp (v6)              ALLOW       Anywhere (v6)
7976/tcp (v6)              ALLOW       Anywhere (v6)
Nginx Full (v6)            ALLOW       Anywhere (v6)
22/tcp (v6)                ALLOW       Anywhere (v6)
```

I've tried the deploy process again and I'm still getting that ambiguous error:

```shell
Getting ready to deploy garden.errbufferoverfl.me to https://distributed.errbufferoverfl.me/
Creating tarball...
Uploading new site content...
/home/runner/work/_actions/hyphacoop/actions-distributed-press/v1.1/dist/index.js:14103
    throw new Error(`Failed to upload the contents of the site: ${json}`);
          ^

Error: Failed to upload the contents of the site: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.fetch (/home/press/api.distributed.press/node_modules/ipfs-utils/src/http.js:140:22)
    at async Object.addAll (file:///home/press/api.distributed.press/node_modules/ipfs-http-client/src/add-all.js:36:17)
    at async IPFSProtocol.sync (file:///home/press/api.distributed.press/protocols/ipfs.ts:163:22)
    at async Promise.all (index 1)
    at async SiteConfigStore.sync (file:///home/press/api.distributed.press/config/sites.ts:65:5)
    at async file:///home/press/api.distributed.press/api/sites.ts:178:7
    at async processRequestFiles (file:///home/press/api.distributed.press/api/sites.ts:20:7)
    at async Object.<anonymous> (file:///home/press/api.distributed.press/api/sites.ts:169:12)
    at run (/home/runner/work/_actions/hyphacoop/actions-distributed-press/v1.1/dist/index.js:14103:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jackyzha0** [comment]
Yeah I think it's an IPFS related error but not sure why it's happening. Seems like it completed on the Hyper side but not IPFS. Lemme ask the team

**Comment by RangerMauve** [comment]
Seems your instance is working well now. https://distributed.errbufferoverfl.me/v1/docs/static/index.html

If you run into trouble again could give us the output of your journalctl at the point you see the error?

**Comment by jackyzha0** [comment]
@RangerMauve I think the instance is healthy but uploads die when syncing to IPFS

**Comment by RangerMauve** [comment]
Interesting. What is the system usage like during upload? I think having 8 GB of RAM is a must for getting it to perform well.

If there are errors during uploading they should be in the system CTL. My gut feeling is it'll be an OOM exception of some sort.

**Comment by errbufferoverfl** [comment]
> I think having 8 GB of RAM is a must for getting it to perform well.
That could explain it, I only allocated the host 1GB of memory to start with so I'll resize the droplet to something larger and check back in with the results.

Would it be worth adding the system requirements to the api.distributed.press docs? 
If I know what the recommendations are I'd be happy to open the PR :)

**Comment by errbufferoverfl** [comment]
🎉 It works! It was absolutely a memory issue! 

Thanks so much @RangerMauve and @jackyzha0!

For anyone else's reference I'm using a digital ocean droplet with the following specs:
- 4vCPU
- 8GB Memory
- 10GB SSD

**Comment by jackyzha0** [comment]
We should probably add better error messages around this particular case though! Thanks for reporting :)

**Comment by RangerMauve** [comment]
Glad it worked! @errbufferoverfl a PR with min requirements would be very welcome. Along with any other info you think would be helpful. I think the best place for it would be the self-hosting docs page https://github.com/hyphacoop/docs.distributed.press/blob/main/pages/self-hosting.mdx

I've started looking into what we can do about OOM stuff and will open an issue about it. From what I understand we'd need to listen on the kubo process crashing which might be tricky to bubble to the error handler in the http response.
